[platformio]
src_dir = .
include_dir = .
default_envs = stm32hc092

[env]
lib_deps = 
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0



[env:stm32hc092]
platform = ststm32
board = disco_f334c8
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
board_build.ldscript = stm32c092rbtx_flash.ld

build_src_filter = 
    +<Core/Src/>
    +<Core/Src/cockpit/>
    +<Drivers/STM32C0xx_HAL_Driver/Src/>
    -<Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
    +<*.s>

build_flags = 
	-ICore/Inc
    -ICore/Inc/cockpit
    -IDrivers/CMSIS/Include
    -IDrivers/STM32C0xx_HAL_Driver/Inc
    -IDrivers/STM32C0xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32C0xx/Include
    -DUSE_HAL_DRIVER
    -DSTM32C092xx


[env:unit_tests]
platform = native
test_framework = unity
test_build_src = true  ; (Updated from deprecated 'test_build_project_src')

build_flags = 
    -Itest
    -Itest/include
    -ICore/Inc
    -ICore/Inc/cockpit
    -DEAGLETRT_STATIC=

build_src_filter = 
    +<Core/Src/cockpit/*.c>
    -<Core/Src/main.c>
    -<Core/Src/dma.c>
    -<Core/Src/gpio.c>
    -<Core/Src/stm32c0xx_*.c>
    -<Core/Src/system_stm32c0xx.c>
    -<Core/Src/sysmem.c>
    -<Core/Src/syscalls.c>

