/******************************************************************************
Finite State Machine
Project: cockpit_fsm
Description: Cockpit FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2025-09-25 16:49:32 +0200
Generated from: fsm.dot
The finite state machine has:
  4 states
  5 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#include "fsm.h"

/*** USER CODE BEGIN MACROS ***/

/*** USER CODE END MACROS ***/

// GLOBALS
// State human-readable names
const char *fsm_state_names[] = { "INIT", "IDLE", "ERROR", "FLASH" };

// List of state functions
fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES] = {
    fsm_do_INIT,  // in state INIT
    fsm_do_IDLE,  // in state IDLE
    fsm_do_ERROR, // in state ERROR
    fsm_do_FLASH, // in state FLASH
};

// Table of transition functions
transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES] = {
    /* states:     INIT              , IDLE              , ERROR             , FLASH              */
    /* INIT    */ { NULL, fsm_init_done, fsm_init_error, NULL },
    /* IDLE    */ { NULL, NULL, fsm_error_detected, fsm_start_flash },
    /* ERROR   */ { NULL, NULL, NULL, NULL },
    /* FLASH   */ { NULL, fsm_flash_done, fsm_error_detected, NULL },
};

// Triggered event
fsm_event_data_t *fsm_fired_event = NULL;

/*** USER CODE BEGIN GLOBALS ***/

/*** USER CODE END GLOBALS ***/

// Function to check if an event has fired
bool fsm_is_event_triggered() {
    return fsm_fired_event != NULL;
}

// Function to trigger an event
void fsm_event_trigger(fsm_event_data_t *event) {
    if (fsm_fired_event != NULL)
        return;
    fsm_fired_event = event ? event : &(fsm_event_data_t){};
}

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state INIT
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR
fsm_state_t fsm_do_INIT(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_IDLE;

    /*** USER CODE BEGIN DO_INIT ***/

    /*** USER CODE END DO_INIT ***/

    switch (next_state) {
        case FSM_STATE_IDLE:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state IDLE
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_IDLE(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_IDLE ***/

    /*** USER CODE END DO_IDLE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_FLASH:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state ERROR
// valid return states: FSM_NO_CHANGE, FSM_STATE_ERROR
fsm_state_t fsm_do_ERROR(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_ERROR ***/

    /*** USER CODE END DO_ERROR ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state FLASH
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_FLASH(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_FLASH ***/

    /*** USER CODE END DO_FLASH ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_FLASH:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from INIT to IDLE
void fsm_init_done(fsm_state_data_t *data) {

    /*** USER CODE BEGIN INIT_DONE ***/

    /*** USER CODE END INIT_DONE ***/
}

// This function is called in 1 transition:
// 1. from INIT to ERROR
void fsm_init_error(fsm_state_data_t *data) {

    /*** USER CODE BEGIN INIT_ERROR ***/

    /*** USER CODE END INIT_ERROR ***/
}

// This function is called in 1 transition:
// 1. from IDLE to FLASH
void fsm_start_flash(fsm_state_data_t *data) {

    /*** USER CODE BEGIN START_FLASH ***/

    /*** USER CODE END START_FLASH ***/
}

// This function is called in 2 transitions:
// 1. from IDLE to ERROR
// 2. from FLASH to ERROR
void fsm_error_detected(fsm_state_data_t *data) {

    /*** USER CODE BEGIN ERROR_DETECTED ***/

    /*** USER CODE END ERROR_DETECTED ***/
}

// This function is called in 1 transition:
// 1. from FLASH to IDLE
void fsm_flash_done(fsm_state_data_t *data) {

    /*** USER CODE BEGIN FLASH_DONE ***/

    /*** USER CODE END FLASH_DONE ***/
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data) {

    /*** USER CODE BEGIN RUN_STATE ***/

    /*** USER CODE END RUN_STATE ***/

    fsm_event_data_t *prev_ev = fsm_fired_event;
    fsm_state_t new_state = fsm_state_table[cur_state](data);
    // Reset event status
    if (prev_ev != NULL)
        fsm_fired_event = NULL;
    if (new_state == FSM_NO_CHANGE)
        new_state = cur_state;
    transition_func_t *transition = fsm_transition_table[cur_state][new_state];
    if (transition)
        transition(data);
    return new_state;
};

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    fsm_state_t cur_state = FSM_STATE_INIT;
    do {
        cur_state = fsm_run_state(cur_state, NULL);
        sleep(1);
    } while (1);
    return 0;
}
#endif
