/******************************************************************************
Finite State Machine
Project: cockpit_fsm
Description: Cockpit FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2025-11-21 22:44:57 +0100
Generated from: fsm.dot
The finite state machine has:
  4 states
  5 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#include "fsm.h"

/*** USER CODE BEGIN MACROS ***/
#include <feedback.h>
#include <indicators.h>
/*** USER CODE END MACROS ***/

// GLOBALS
// State human-readable names
const char *fsm_state_names[] = { "init", "idle", "error", "flash" };

// List of state functions
fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES] = {
    fsm_do_init,  // in state init
    fsm_do_idle,  // in state idle
    fsm_do_error, // in state error
    fsm_do_flash, // in state flash
};

// Table of transition functions
transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES] = {
    /* states:     init              , idle              , error             , flash              */
    /* init    */ { NULL, fsm_init_done, fsm_init_error, NULL },
    /* idle    */ { NULL, NULL, fsm_error_detected, fsm_start_flash },
    /* error   */ { NULL, NULL, NULL, NULL },
    /* flash   */ { NULL, fsm_flash_done, fsm_error_detected, NULL },
};

// Triggered event
fsm_event_data_t *fsm_fired_event = NULL;

/*** USER CODE BEGIN GLOBALS ***/
/* Wrapper function for Mushroom 1 */
static bool prv_read_m1_pin(void) {
    return (HAL_GPIO_ReadPin(SHUTDOWN_STATUS_A_GPIO_Port, SHUTDOWN_STATUS_A_Pin) == GPIO_PIN_RESET);
}

/* Wrapper function for Mushroom 2 */
static bool prv_read_m2_pin(void) {
    return (HAL_GPIO_ReadPin(SHUTDOWN_STATUS_B_GPIO_Port, SHUTDOWN_STATUS_B_Pin) == GPIO_PIN_RESET);
}

/*Wrapper function for AMS led*/
static void prv_set_ams_indicator(bool state) {
    HAL_GPIO_WritePin(AMS_LED_GPIO_Port, AMS_LED_Pin, state ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/*Wrapper function for IMD led*/
static void prv_set_imd_indicator(bool state) {
    HAL_GPIO_WritePin(IMD_LED_GPIO_Port, IMD_LED_Pin, state ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/*Wrapper function for TS_OFF led*/
static void prv_set_ts_off_indicator(bool state) {
    HAL_GPIO_WritePin(TS_OFF_LED_GPIO_Port, TS_OFF_LED_Pin, state ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/*Wrapper function for mission profile indicators*/
static void prv_set_mission_indicator(bool state, uint8_t pin) {
    if (pin >= MISSION_PINS) {
        return; // Invalid pin
    }
    uint16_t pins[] = { LED_BIT_0_Pin, LED_BIT_1_Pin, LED_BIT_2_Pin };
    GPIO_TypeDef *ports[] = { LED_BIT_0_GPIO_Port, LED_BIT_1_GPIO_Port, LED_BIT_2_GPIO_Port };
    HAL_GPIO_WritePin(ports[pin], pins[pin], state ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

struct FeedbackHandler mushroom_A = {
    .read_fb = prv_read_m1_pin,
    .fb_name = "Cockpit Mushroom",
};

struct FeedbackHandler mushroom_B = {
    .read_fb = prv_read_m2_pin,
    .fb_name = "Rear L Mushroom",
};

struct FeedbackHandler *mushroom_global_handler[] = {
    &mushroom_A,
    &mushroom_B,
};

struct IndicatorsFunctionSet indicator_functions = {
    .ams = prv_set_ams_indicator,
    .imd = prv_set_imd_indicator,
    .ts_off = prv_set_ts_off_indicator,
    .mission = prv_set_mission_indicator,
};

// EXTI Callbacks to be called from HAL
void HAL_GPIO_EXTI_falling_Callback(uint16_t GPIO_Pin) {
    if (GPIO_Pin == SHUTDOWN_STATUS_A_Pin) {
        feedback_falling_edge_callback(&mushroom_A);
    } else if (GPIO_Pin == SHUTDOWN_STATUS_B_Pin) {
        feedback_falling_edge_callback(&mushroom_B);
    }
};

void HAL_GPIO_EXTI_rising_Callback(uint16_t GPIO_Pin) {
    if (GPIO_Pin == SHUTDOWN_STATUS_A_Pin) {
        feedback_rising_edge_callback(&mushroom_A);
    } else if (GPIO_Pin == SHUTDOWN_STATUS_B_Pin) {
        feedback_rising_edge_callback(&mushroom_B);
    }
}
/*** USER CODE END GLOBALS ***/

// Function to check if an event has fired
bool fsm_is_event_triggered() {
    return fsm_fired_event != NULL;
}

// Function to trigger an event
void fsm_event_trigger(fsm_event_data_t *event) {
    if (fsm_fired_event != NULL)
        return;
    fsm_fired_event = event ? event : &(fsm_event_data_t){};
}

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR
fsm_state_t fsm_do_init(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_IDLE;

    /*** USER CODE BEGIN DO_INIT ***/
    // Initialization functions
    if (feedback_init(mushroom_global_handler, (size_t)2) != FEEDBACK_NOT_PRESSED) {
        next_state = FSM_STATE_ERROR;
    }

    if (!indicators_init(&indicator_functions)) {
        next_state = FSM_STATE_ERROR;
    }

    // Power on tests
    if (feedback_get_state() == FEEDBACK_PRESSED) {
        // At least one mushroom button is pressed during initialization (this is redundant with feedback_init check)
        next_state = FSM_STATE_ERROR;
    }
    /*** USER CODE END DO_INIT ***/

    switch (next_state) {
        case FSM_STATE_IDLE:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_idle(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_IDLE ***/
    //TODO: Implement can module to receive commands and update led_state_global accordingly

    indicators_update();
    indicators_update_mission();

    if (feedback_get_state() == FEEDBACK_PRESSED) {
        char *names[FEEDBACK_MAX_HANDLERS];
        size_t pressed_count = feedback_get_pressed(names, FEEDBACK_MAX_HANDLERS);
        // Handle pressed feedback buttons if needed
    }
    /*** USER CODE END DO_IDLE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_FLASH:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state error
// valid return states: FSM_NO_CHANGE, FSM_STATE_ERROR
fsm_state_t fsm_do_error(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_ERROR ***/

    /*** USER CODE END DO_ERROR ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_flash(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_FLASH ***/

    /*** USER CODE END DO_FLASH ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_FLASH:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from init to idle
void fsm_init_done(fsm_state_data_t *data) {

    /*** USER CODE BEGIN INIT_DONE ***/

    /*** USER CODE END INIT_DONE ***/
}

// This function is called in 1 transition:
// 1. from init to error
void fsm_init_error(fsm_state_data_t *data) {

    /*** USER CODE BEGIN INIT_ERROR ***/

    /*** USER CODE END INIT_ERROR ***/
}

// This function is called in 1 transition:
// 1. from idle to flash
void fsm_start_flash(fsm_state_data_t *data) {

    /*** USER CODE BEGIN START_FLASH ***/

    /*** USER CODE END START_FLASH ***/
}

// This function is called in 2 transitions:
// 1. from idle to error
// 2. from flash to error
void fsm_error_detected(fsm_state_data_t *data) {

    /*** USER CODE BEGIN ERROR_DETECTED ***/

    /*** USER CODE END ERROR_DETECTED ***/
}

// This function is called in 1 transition:
// 1. from flash to idle
void fsm_flash_done(fsm_state_data_t *data) {

    /*** USER CODE BEGIN FLASH_DONE ***/

    /*** USER CODE END FLASH_DONE ***/
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data) {

    /*** USER CODE BEGIN RUN_STATE ***/

    /*** USER CODE END RUN_STATE ***/

    fsm_event_data_t *prev_ev = fsm_fired_event;
    fsm_state_t new_state = fsm_state_table[cur_state](data);
    // Reset event status
    if (prev_ev != NULL)
        fsm_fired_event = NULL;
    if (new_state == FSM_NO_CHANGE)
        new_state = cur_state;
    transition_func_t *transition = fsm_transition_table[cur_state][new_state];
    if (transition)
        transition(data);
    return new_state;
};

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    fsm_state_t cur_state = FSM_STATE_INIT;
    do {
        cur_state = fsm_run_state(cur_state, NULL);
        sleep(1);
    } while (1);
    return 0;
}
#endif
